[package]
name = "mod_study"
version = "0.1.0"
authors = ["akitasummer <akitasummer@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
debug = true # 在发布构建中启动调试标记